GeneticAlgorithm: GeneticAlgorithm.GraphLibrary.Graph Class Reference
GeneticAlgorithm.GraphLibrary.Graph Class Reference
This class.
Public Member Functions
def __init__
This class models a weighted, directed graph.
def updateW
Update the weight matrix to be consistent with the current node positions.
def pathLength
Compute the length of a path.
def __str__
A human readable representation of the graph.
def __setattr__
Validate that the attributes V and W are consistent.
def randomizeNodePositions
def plot
Plot the graph using matplotlib.
Public Attributes
V
W
Detailed Description
This class.
Definition at line 17 of file GraphLibrary.py.
Constructor & Destructor Documentation
GeneticAlgorithm::GraphLibrary.Graph::__init__ (V, E = None, W = [], N = 5, kwargs)
This class models a weighted, directed graph.
Parameters:
V A list of of node coordinates, if it is not provided, a random set of coordinates will be produced
W A matrix (or list of lists) that contains the edge costs, if not provided, the graph will compute the euclidean distance between nodes
N if both V and W are omitted,
W must be of size len(V) x len(V) to contain the weights of the graph edge; W[j][i] -> is the cost of going from j to i, nonexisting edges should be represented using the None object; If this parameter is not
Definition at line 25 of file GraphLibrary.py.
Member Function Documentation
def GeneticAlgorithm::GraphLibrary.Graph::__setattr__ (self, attribute, value)
Validate that the attributes V and W are consistent.
Definition at line 77 of file GraphLibrary.py.
References GeneticAlgorithm.GraphLibrary.Graph.V.
Referenced by GeneticAlgorithm.Core.GABaseObject.__init__().
GeneticAlgorithm::GraphLibrary.Graph::__str__ (self)
A human readable representation of the graph.
Returns:
Return a multi-line string representation of the graph
Reimplemented from GeneticAlgorithm.Core.GABaseObject.
Definition at line 70 of file GraphLibrary.py.
References GeneticAlgorithm.GraphLibrary.Graph.V, and GeneticAlgorithm.GraphLibrary.Graph.W.
GeneticAlgorithm::GraphLibrary.Graph::pathLength (self, path)
Compute the length of a path.
Parameters:
path An iterable that returns the nodes in the desired path
Definition at line 59 of file GraphLibrary.py.
References GeneticAlgorithm.GraphLibrary.Graph.W.
GeneticAlgorithm::GraphLibrary.Graph::plot (self, paths = None, axes = None)
Plot the graph using matplotlib.
Parameters:
paths A list of tuples. Each tuple contains a path to plot over the graph
Todo:
Support 3-D plots and path animations
Definition at line 102 of file GraphLibrary.py.
References GeneticAlgorithm.GraphLibrary.Graph.V.
def GeneticAlgorithm.GraphLibrary.Graph.randomizeNodePositions (self, n = None, d = 2)
Definition at line 92 of file GraphLibrary.py.
References GeneticAlgorithm.GraphLibrary.Graph.updateW(), and GeneticAlgorithm.GraphLibrary.Graph.V.
GeneticAlgorithm::GraphLibrary.Graph::updateW (self)
Update the weight matrix to be consistent with the current node positions.
Definition at line 42 of file GraphLibrary.py.
References GeneticAlgorithm::GraphLibrary.euclideanDistance(), GeneticAlgorithm.GraphLibrary.Graph.V, and GeneticAlgorithm.GraphLibrary.Graph.W.
Referenced by GeneticAlgorithm.GraphLibrary.Graph.randomizeNodePositions().
Member Data Documentation
GeneticAlgorithm::GraphLibrary.Graph::V
Definition at line 25 of file GraphLibrary.py.
Referenced by GeneticAlgorithm.GraphLibrary.Graph::__setattr__(), GeneticAlgorithm.GraphLibrary.Graph::__str__(), GeneticAlgorithm.GraphLibrary.Graph::plot(), GeneticAlgorithm.GraphLibrary.Graph::randomizeNodePositions(), and GeneticAlgorithm.GraphLibrary.Graph::updateW().
GeneticAlgorithm::GraphLibrary.Graph::W
Definition at line 25 of file GraphLibrary.py.
Referenced by GeneticAlgorithm.GraphLibrary.Graph.__str__(), GeneticAlgorithm.GraphLibrary.Graph.pathLength(), and GeneticAlgorithm.GraphLibrary.Graph.updateW().
The documentation for this class was generated from the following file:
src/GeneticAlgorithm/GraphLibrary.py