GeneticAlgorithm: GeneticAlgorithm.Core.Individual Class Reference
GeneticAlgorithm.Core.Individual Class Reference
This class is a container intended to store all information relevant to an individual.
Public Member Functions
def __init__
The individual constructor.
def randomize
Call self.genotype.randomize()
def valuesToStr
Return the string representation of the values of all properties.
def propertiesToStr
Return the names of all properties in the order that valuesToStr prints them.
def __str__
Return a string representation of self, accordin to the function toStr.
def crossover
Crossover self and another genotype.
def mutate
call mutate() on self's chromosome
Detailed Description
This class is a container intended to store all information relevant to an individual.
This class is a container, intended to store all information relevant to an individual, including but not limited to:
Genotype
Phenotype
Evaluation
Non-generational information, such as:
Age
Fitness moving average
Fitness variance
Definition at line 238 of file Core.py.
Constructor & Destructor Documentation
GeneticAlgorithm::Core.Individual::__init__ (self, genotype = Genotype(), fitness = 0.0, kwargs)
The individual constructor.
The minimum expression of an individual is to have a genotype and fitness value. Any other imaginable property can be added at this stage by passing a named parameter
Definition at line 243 of file Core.py.
Member Function Documentation
GeneticAlgorithm::Core.Individual::__str__ (self)
Return a string representation of self, accordin to the function toStr.
The behavior of this function can be easily changed with the following technique:
  Individual.__str__ = lambda(self) : self.toStr(propertyList=['property1', 'property2', ...])
Where the propertyList is a list of strings containing the names of the properties to display
Reimplemented from GeneticAlgorithm.Core.GABaseObject.
Definition at line 273 of file Core.py.
References GeneticAlgorithm.Core.Individual.valuesToStr().
GeneticAlgorithm::Core.Individual::crossover (self, other)
Crossover self and another genotype.
Returns:
an Individual object containing the crossover of self and other
Definition at line 279 of file Core.py.
GeneticAlgorithm::Core.Individual::mutate (self)
call mutate() on self's chromosome
Definition at line 286 of file Core.py.
GeneticAlgorithm::Core.Individual::propertiesToStr (self, separator = '\t')
Return the names of all properties in the order that valuesToStr prints them.
Parameters:
separator The string that separates property names
Returns:
The names properties separated by the optional separator string
Definition at line 262 of file Core.py.
GeneticAlgorithm::Core.Individual::randomize (self)
Call self.genotype.randomize()
Definition at line 248 of file Core.py.
Referenced by GeneticAlgorithm.Core.Population.__init__().
GeneticAlgorithm::Core.Individual::valuesToStr (self, separator = '\t')
Return the string representation of the values of all properties.
Parameters:
separator The string that separates property values
Returns:
The string representation of the values of all properties separated by the optional separator string
Definition at line 255 of file Core.py.
Referenced by GeneticAlgorithm.Core.Individual.__str__().
The documentation for this class was generated from the following file:
src/GeneticAlgorithm/Core.py