GeneticAlgorithm: GeneticAlgorithm.Core.Genotype Class Reference
GeneticAlgorithm.Core.Genotype Class Reference
The base Genotype class from which all chromosomes must derived.
Public Member Functions
def __init__
(self, **kwargs)
def __setattr__
This function allows typechecking to occur for segments, without the need for accessors.
def randomize
def addSegment
Add a segment to the genotype.
def crossover
Perform a one-point crossover between self an and other Genotype.
def mutate
Select one segment randomly and call mutate() on it.
def __str__
The string representation of the object.
Public Attributes
segments
Detailed Description
The base Genotype class from which all chromosomes must derived.
The Genotype class is primarily a container that supports the minimum GA interface:
randomize(self)
mutate(self)
crossover(self, other)
Definition at line 177 of file Core.py.
Constructor & Destructor Documentation
def GeneticAlgorithm.Core.Genotype.__init__ (self, kwargs = [])
(self, **kwargs)
The default behavior for GA objects
The default behavior of GA objects is to accept any kind of named arguments on their constructor, and save them in properties with the same name.
Reimplemented from GeneticAlgorithm.Core.GABaseObject.
Definition at line 181 of file Core.py.
Member Function Documentation
GeneticAlgorithm::Core.Genotype::__setattr__ (self, attribute, value)
This function allows typechecking to occur for segments, without the need for accessors.
Definition at line 185 of file Core.py.
References GeneticAlgorithm.Core.Genotype.addSegment().
Referenced by GeneticAlgorithm.Core.GABaseObject.__init__().
GeneticAlgorithm::Core.Genotype::__str__ (self)
The string representation of the object.
The default str() representation of GA objects is to return repr()
Reimplemented from GeneticAlgorithm.Core.GABaseObject.
Definition at line 218 of file Core.py.
References GeneticAlgorithm.Core.Genotype.segments.
GeneticAlgorithm::Core.Genotype::addSegment (self, segment)
Add a segment to the genotype.
Definition at line 199 of file Core.py.
Referenced by GeneticAlgorithm.Core.Genotype.__setattr__().
GeneticAlgorithm::Core.Genotype::crossover (self, other)
Perform a one-point crossover between self an and other Genotype.
Returns:
A Genotype object that contains the new genotype
Warning:
Segments are references to objects. It is recommended that
Definition at line 206 of file Core.py.
References GeneticAlgorithm.Core.Genotype.segments.
GeneticAlgorithm::Core.Genotype::mutate (self)
Select one segment randomly and call mutate() on it.
Definition at line 213 of file Core.py.
References GeneticAlgorithm.Core.Genotype.segments.
def GeneticAlgorithm.Core.Genotype.randomize (self)
Definition at line 194 of file Core.py.
References GeneticAlgorithm.Core.Genotype.segments.
Referenced by GeneticAlgorithm.Core.Population.__init__().
Member Data Documentation
GeneticAlgorithm::Core.Genotype::segments
Definition at line 181 of file Core.py.
Referenced by GeneticAlgorithm.Core.Genotype::__str__(), GeneticAlgorithm.Core.Genotype::crossover(), GeneticAlgorithm.Core.Genotype::mutate(), and GeneticAlgorithm.Core.Genotype::randomize().
The documentation for this class was generated from the following file:
src/GeneticAlgorithm/Core.py