GeneticAlgorithm: GADemo.NumOnes Class Reference
GADemo.NumOnes Class Reference
An evaluation operator that computes the number of ones in a segment whose data can be converted to binary using the bin() function.
Public Member Functions
def segmentOnes
Compute the number of ones in one genotype segment.
def evaluateIndividual
Call segmentOnes for each segment on the genotype, and add them all together to produce a fitness function.
Detailed Description
An evaluation operator that computes the number of ones in a segment whose data can be converted to binary using the bin() function.
Definition at line 5 of file GADemo.py.
Member Function Documentation
def GADemo.NumOnes.evaluateIndividual (self, individual)
Call segmentOnes for each segment on the genotype, and add them all together to produce a fitness function.
Reimplemented from GeneticAlgorithm.EvaluationOperators.BaseEvaluationOperator.
Definition at line 11 of file GADemo.py.
References GADemo.NumOnes.segmentOnes().
Referenced by GeneticAlgorithm.EvaluationOperators.BaseEvaluationOperator.evaluate().
GADemo.NumOnes::segmentOnes (self, segment)
Compute the number of ones in one genotype segment.
Definition at line 8 of file GADemo.py.
Referenced by GADemo.NumOnes.evaluateIndividual().
The documentation for this class was generated from the following file:
src/examples/GADemo.py